version: '3.1'

services:
  db:
    container_name: fbs_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    networks:
      - fbs_net
    # don't forget backup volume
  queue-db:
    container_name: fbs_queue_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - fbs_net
    depends_on:
      - db
    
  # nestjs-queue:
  #   container_name: fbs_nestjs_queue
  #   build:
  #     context: ./nestjs-queue/
  #   volumes:
  #     - ./uploads:/uploads
  #     # - /usr/src/app/node_modules
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - DB_MYSQL_USER=root
  #     - DB_MYSQL_PASS=root
  #     - DB_MYSQL_HOST=db
  #     - DB_MYSQL_TYPE=mysql
  #     - DB_MYSQL_PORT=3306
  #     - DB_MYSQL_DBNAME=test_db
  #     - DB_REDIS_HOST=queue-db
  #     - DB_REDIS_PORT=6379
  #   depends_on:
  #     - queue-db

networks:
  fbs_net: