version: '3.1'

services:
  db:
    container_name: fbs_mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    # don't forget backup volume
  queue-db:
    container_name: fbs_queue_redis
    image: redis
    restart: always
    ports:
      - "6379:6379"